// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UploadBigFileOKCode is the HTTP code returned for type UploadBigFileOK
const UploadBigFileOKCode int = 200

/*UploadBigFileOK Successful

swagger:response uploadBigFileOK
*/
type UploadBigFileOK struct {
}

// NewUploadBigFileOK creates UploadBigFileOK with default headers values
func NewUploadBigFileOK() *UploadBigFileOK {

	return &UploadBigFileOK{}
}

// WriteResponse to the client
func (o *UploadBigFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
