// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// UploadBigFileMaxParseMemory sets the maximum size in bytes for
// the multipart form parser for this operation.
//
// The default value is 32 MB.
// The multipart parser stores up to this + 10MB.
var UploadBigFileMaxParseMemory int64 = 32 << 20

// NewUploadBigFileParams creates a new UploadBigFileParams object
//
// There are no default values defined in the spec.
func NewUploadBigFileParams() UploadBigFileParams {

	return UploadBigFileParams{}
}

// UploadBigFileParams contains all the bound params for the upload big file operation
// typically these are obtained from a http.Request
//
// swagger:parameters UploadBigFile
type UploadBigFileParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: formData
	*/
	BigFile io.ReadCloser
	/*First Name
	  Required: true
	  In: path
	*/
	FirstName string
	/*Last Name
	  Required: true
	  In: path
	*/
	LastName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadBigFileParams() beforehand.
func (o *UploadBigFileParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(UploadBigFileMaxParseMemory); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}

	bigFile, bigFileHeader, err := r.FormFile("bigFile")
	if err != nil {
		res = append(res, errors.New(400, "reading file %q failed: %v", "bigFile", err))
	} else if err := o.bindBigFile(bigFile, bigFileHeader); err != nil {
		// Required: true
		res = append(res, err)
	} else {
		o.BigFile = &runtime.File{Data: bigFile, Header: bigFileHeader}
	}

	rFirstName, rhkFirstName, _ := route.Params.GetOK("firstName")
	if err := o.bindFirstName(rFirstName, rhkFirstName, route.Formats); err != nil {
		res = append(res, err)
	}

	rLastName, rhkLastName, _ := route.Params.GetOK("lastName")
	if err := o.bindLastName(rLastName, rhkLastName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBigFile binds file parameter BigFile.
//
// The only supported validations on files are MinLength and MaxLength
func (o *UploadBigFileParams) bindBigFile(file multipart.File, header *multipart.FileHeader) error {
	return nil
}

// bindFirstName binds and validates parameter FirstName from path.
func (o *UploadBigFileParams) bindFirstName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.FirstName = raw

	return nil
}

// bindLastName binds and validates parameter LastName from path.
func (o *UploadBigFileParams) bindLastName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.LastName = raw

	return nil
}
