// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UploadBigFileHandlerFunc turns a function with the right signature into a upload big file handler
type UploadBigFileHandlerFunc func(UploadBigFileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadBigFileHandlerFunc) Handle(params UploadBigFileParams) middleware.Responder {
	return fn(params)
}

// UploadBigFileHandler interface for that can handle valid upload big file params
type UploadBigFileHandler interface {
	Handle(UploadBigFileParams) middleware.Responder
}

// NewUploadBigFile creates a new http.Handler for the upload big file operation
func NewUploadBigFile(ctx *middleware.Context, handler UploadBigFileHandler) *UploadBigFile {
	return &UploadBigFile{Context: ctx, Handler: handler}
}

/* UploadBigFile swagger:route POST /{firstName}_{lastName} uploadBigFile

A Place where a user can upload a big file

A Place where a user can upload a big file

*/
type UploadBigFile struct {
	Context *middleware.Context
	Handler UploadBigFileHandler
}

func (o *UploadBigFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUploadBigFileParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
