// Code generated by go-swagger; DO NOT EDIT.

// Package restapi go-swagger custom extension scratch pad
//
//  go-swagger custom extension scratch pad
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0.0
//  Contact: David Macpherson<david@tensorworks.com.au>
//
//  Consumes:
//    - multipart/form-data
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
